name: Update blog posts
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    # Runs every 5 minutes
    - cron: '*/1 * * * *'
    

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: MEDIUM
          feed_list: "https://medium.com/feed/@yehezkiell"
