name: Latest Medium Post
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  update-readme-with-medium:
    name: Update this repo's README with latest activity from Medium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yehezkiell/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM"
          commit_message: "Updated readme with the latest medium data"
          feed_list: "https://medium.com/feed/@yehezkiell"
